inherit_from: ./ruby-2.0.yml

Style/Encoding:
  Enabled: false

Style/HashConversion:
  Enabled: false

# Percent delimiters are not supported until Ruby 2.0
Style/PercentLiteralDelimiters:
  Enabled: false

Style/FileNull:
  Enabled: false
