inherit_from: ./ruby-2.3.yml

AllCops:
  TargetRubyVersion: 2.2

# The below cops are for features not available until Ruby 2.3 but,
# as of this writing, the cops don't correctly use the TargetRubyVersion.

Style/HashFetchChain:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Style/SafeNavigation:
  Enabled: false
